######################################################################
# Automatically generated by qmake (3.0) ?? ????. 9 17:42:00 2014
######################################################################

TEMPLATE = app
TARGET = Tea.Final

QMAKE_CXX = clang++
QMAKE_LINK = clang++
QMAKE_CXXFLAGS += -std=c++11 

QT += widgets webkitwidgets

SOURCES += main.cpp
include(face/include.inc)
