######################################################################
# Automatically generated by qmake (3.0) Mon Feb 17 00:39:56 2014
######################################################################

TEMPLATE = app
TARGET = Tea.Final
INCLUDEPATH += .

QMAKE_CXX = clang++
QMAKE_LINK = clang++
QMAKE_CXXFLAGS += -std=c++11 

QT += widgets multimedia xml

include(daemon/include.inc)
include(face/include.inc)

# Input
SOURCES += main.cpp
